---
- name: Teste de ping nos servidores
  hosts: all
  tasks:
    - name: Ping nos servidores
      ping: google.com

    - name: Exibir mensagem
      debug:
        msg: "Conectividade testada com sucesso!"
