---
- name: Atualizar pacotes
  hosts: all
  become: yes  # Indica que os comandos devem ser executados com sudo

  tasks:
    - name: Atualizar repositórios
      apt:
        update_cache: yes
        force_apt_get: yes

    - name: Realizar upgrade dos pacotes
      apt:
        upgrade: yes
        autoremove: yes
        autoclean: yes
        force_apt_get: yes